### PR TITLE
Prebuild list of redundancies

### PR DESCRIPTION
**Pull request by kemitchell**
First and foremost: Great stuff! Thanks for much for taking the time.

This PR pulls the code that generates a list of redundant words-numeral regexps into a separate script that generates a JSON file containing that list. `index.js` now `require()`s that prebuilt list when loaded. An npm `prepublish` script makes sure the redundancies list is rebuilt before each publication to npm, and a `pretest` script rebuilds the list before running tests.

I also went ahead and killed some dead generation code, and used a preexisting package to escape strings destined to be `RegExp`s.

None of this should have been obvious to you, and it all amounts to an optimization concession to eventual packing in commonform.org. Basically, if the list of phrases to replace will be finite, I'd rather prebuild it at the expense of more code in the package than compute it each time the package is loaded. The added weight, such as it is, is offset by making the packages used for generation `devDependencies` rather than runtime `dependencies` of the module the package exports, so they won't have to be part of the JavaScript bundle for users in the browser:

``` shellsession
$ git checkout origin/master
$ npm i -g browserify
$ browserify index.js > master.js
$ git checkout kemitchell/prebuild-list-of-redundancies
$ browserify index.js > prebuilt.js
$ du -b master.js prebuilt.js
14074   master.js
5410    prebuilt.js
```

The list of redundancies is highly repetitive English text, so it compresses really nicely:

``` shellsession
$ npm run prepublish
$ du -b redundancies.json
2442    redundancies.json
$ gzip redundancies.json
$ du -b redundancies.json.gz
552    redundancies.json.gz
```

This is the approach commonform-archaic and commonform-critique use. Both of those packages depend on separate packages with the list of search strings, but here I think it makes sense to keep it all together.

This is 100% implementation, a SemVer patch bump at most. `npm version minor && npm publish`, if you don't know already.

Again, thanks so much for this!

### CODE REVIEW

**Comment by kemitchell** [comment]
Related: commonform/commonform-critique#2

**Comment by anseljh** [comment]
Thanks! Your changes all make sense. The packaging stuff is still slightly voodoo-like, but I'm learning.

**Comment by kemitchell** [comment]
npm is very different than what you might have seen in the Python or Ruby worlds, even with `virtualenv` or Bundler. In a good way!

The core docs are:

https://nodejs.org/api/modules.html

https://github.com/npm/node-semver

That's pretty dry stuff. You'll pick it up well enough as you go.

**Comment by anseljh** [comment]
Yes, I like `npm` a lot so far. I've been going through the docs. It all
makes sense for the most part.

**Pull request merged**
