### PR TITLE
Case-insensitive regular expressions

### PR DESCRIPTION
**Pull request by kemitchell**
You could do a patch bump for this. I'll catch it in my next deploy.

### CODE REVIEW

**Comment by anseljh** [comment]
Thanks! Landed in 0.2.1.

I realized I should also make the dash in the regexes optional. See #8.

**Comment by kemitchell** [comment]
Redeployed.

https://commonform.org/forms/ee938e6a83135eb0130e3d622053e4408a9f4f055c47c63201bd4ba96f3c0b52

Let me know if it isn't clear yet why this

 https://github.com/commonform/commonform-critique/blob/master/package.json#L10

picked up new 0.2.1

**Comment by anseljh** [comment]
Nope—I understand that.

**Comment by anseljh** [comment]
However,  your link is giving me this JS error dialog:

```
Internal XMLHttpRequest Error
```

**Comment by kemitchell** [comment]
https://commonform.org/forms/818cc8cdbab511fabc4b8e209d049b435540607281a3fae75afd5c4c8325e972

Pasted the wrong link.

**Pull request merged**
